vim.g.use_codicons = true
local icons = {
	separators = {
		slant = { left = "", right = "" },
		rounded = { left = "", right = "" },
		arrow = { left = "", right = "" },
		straight = { left = "|", right = "|" },
		arrow_bracket = { left = "", right = "" },
		rounded_bracket = { left = "", right = "" },
		blank = { left = "", right = "" },
	},
	borders = {
		square = {
			top = "─",
			bottom = "─",
			left = "│",
			right = "│",
			top_left = "┌",
			top_right = "┐",
			bottom_left = "└",
			bottom_right = "┘",
			inter_left = "├",
			inter_right = "┤",
		},
		round = {
			top = "─",
			bottom = "─",
			left = "│",
			right = "│",
			top_left = "╭",
			top_right = "╮",
			bottom_left = "╰",
			bottom_right = "╯",
			inter_left = "├",
			inter_right = "┤",
		},
	},
	kind = {
		Array = "",
		Boolean = "",
		Class = "",
		Color = "",
		Constant = "",
		Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "",
		Folder = "",
		Function = "󰊕",
		Interface = "",
		Key = "",
		Keyword = "",
		Method = "",
		Misc = "",
		Module = "",
		Namespace = "",
		Null = "",
		Number = "",
		Object = "",
		Operator = "",
		Package = "",
		Property = "",
		Reference = "",
		Snippet = "",
		String = "",
		Struct = "",
		Text = "",
		TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "",
	},
	ui = {
		ArrowClosed = "",
		ArrowOpen = "",
		ArrowFillClosed = "",
		ArrowFillOpen = "",
		ArrowNavLeft = " ",
		ArrowNavRight = " ",
		Lock = " ",
		Circle = " ",
		Circle_Empty = " ",
		Dot = "●",
		Mason = "◍ ",
		Diamond = "◆",
		Close = "",
		NewFile = " ",
		Search = " ",
		Multi_Select = " ",
		Caret_Arrow = " ",
		Lightbulb = "",
		Project = " ",
		Dashboard = " ",
		History = " ",
		Comment = " ",
		Bug = " ",
		Code = " ",
		Telescope = " ",
		Gear = " ",
		Package = " ",
		List = " ",
		BulletList = " ",
		SignIn = " ",
		SignOut = " ",
		Check = " ",
		Fire = " ",
		Note = " ",
		BookMark = " ",
		Pencil = "󰏫 ",
		Question = " ",
		ChevronRight = "",
		Table = "",
		Calendar = "",
		CloudDownload = "",
		Stacks = " ",
		Scopes = "",
		Watches = "󰍉 ",
		Ellipses = "…",
		Tab = "󰌒 ",
		House = " ",
		Wand = " ",
		Tag = " ",
	},
	debug = {
		Pause = "",
		Play = "",
		Step_into = "",
		Step_over = "",
		Step_out = "",
		Step_back = "",
		Run_last = "",
		Terminate = "",
		Breakpoint = "",
		BreakpointCond = "",
		BreakpointLog = "",
	},
	characters = {
		eol = "↲",
		extends = "›",
		nbsp = "␣",
		precedes = "‹",
		space = "•",
		tab = "|->",
		trail = "×",
		indent = "▏",
		indent_focus = "▎",
	},
	diagnostic = {
		error = "󰅙 ",
		warn = " ",
		hint = "󰌵 ",
		info = " ",
	},
	git = {
		Add = "+",
		Mod = "~",
		Remove = "-",
		Octoface = " ",
		Branch = "",
		signs = {
			add = "▎",
			mod = "▎",
			delete = "▁",
			top_delete = "▔",
			change_delete = "~",
			untracked = "┊",
		},
	},
	arrows = {
		left = " ",
		down = " ",
		up = " ",
		right = " ",
	},
}

return icons
