require("faith.options")
require("faith.mappings")
require("faith.statusline")
require("faith.bootstrap")
require("faith.globals")
require("faith.shell")
require("faith.spell")
require("faith.filetypes")

require("faith.neovide")
