require("faith.plugins")
require("impatient")
require("faith.lsp")
require("faith.settings")
require("faith.session")
require("faith.keymap")
require("faith.mappings")
require("faith.listchars")
require("faith.snippets.comment_nvim")
require("faith.modules.tabline")
-- require("faith.winbar")
